###########################################
#  ___                  _     ____   ___  #
# / _ \ _   _  ___  ___| |_  |___ \ / _ \ #
#| | | | | | |/ _ \/ __| __|   __) | | | |#
#| |_| | |_| |  __/\__ \ |_   / __/| |_| |#
# \__\_\\__,_|\___||___/\__| |_____|\___/ #
#                                         #
###########################################
# ---------------------------PART II-------------------------------
from collections import deque

my_input = """
T#TT#TT#TTTT#TT#TTTTTTTTTT#TTTT#TT#T#T#TT#TTTT#TTTTT#TT#TTTTT#TT#TTTTTT#TTTTTT#TT#TTT#TT#TTTT#TTTTTTTTTTTT#TT#T#TTT#TT#T#TTTTTTTT#T#TT#TTTTTTTT#TTT#TTT#TT#TT#T
.TTTTTTTTT#TTTTTTT#TTTT#TTTTTTTTTTTTTTTTTTTTTTTTT#TTTTTTTT#TTTTTTTTTT#TTTTT#TTTTTTTTTTTTTTTTTTTT#TT#TT#TTTTTTTTTTTTTTTTTTTT#TTT#TTTTTTTT#T#TT#TTTTTTTTTTTTTTTT.
..TTTTT#TTTTTT#T#TTTT#TTTTTTTTTTTTT#TTTTTTTTTTTTTTT#T#T#TT#T#TTT#TT#TTTTTTTTTT#TTTTTTTTTTTT#T#TTTTT#TTTTT#TTT#TTTTTT#TTTTTTTTTTTTTTT#TTTTTTTTTTT#T#TTTTTTTTTT..
...#TTTTTT#TTTTTTTTTTTTT#TT#TTT#TTTTTT#TTTTT#TTTTTTTTTTTTT#TTTTTTTTTTTTT#T#T#TTTT#TT#TT#TTTTTTTTTTT#TTTTTTT#TTTT#T#TTTT#TTTTTTTTTTTTTTTTTTTTTT#TTTTTTTT#TT#T...
....T#TTTTTTT#TTT#TTTTTTTTTTT#TTTTTTTTTTT#TTTTT#TTTT#############TTTT#TTTTTTTTTTTTTTTTTTTTTTT############TTTTT#TTTTTTTTTTTTTT#T#TTTT#T#TT#TTTTTTTTTT#TTTTTT....
.....TTTTTTTTTTTTTTTTTTTTTT#TTTTTT#TTTTTTTT#TTTTT###################TTTTTTTTTTTTTTTTTTTTTT###################TTT#TT#TTTTTT#TTTTTTTTTTTTTTTTTTTT#T#TTTTTT#T.....
......T#TT#TTTT#TTTTTTTT#TTTTT#TTTTTTTTTTTTTTTT######TTTTTTTTTTT#######TT#T#TTT#TT#TTTT#######TTTTTTTTTT#######TTTTTTTTTTTTTTTTTTTT#T#TTTTTT#TTTTTTTT#TTT......
.......TTTTTT#TTT#TTT#TTTTTTTTTT#TT#TTT#TTTTT######TTTTTTTTTTTTTTT######TTTTTTTTTTTTT######TTTTTTTTTTTTTTTT#####TTTT#T#TTTTTT#TT#TTTTTT#TTTTTTTTTT#TTTTT.......
........#T#TTTTTTTTTTTTTTTT#TTTTTTTTTTTTTTTT#####TTTTT######TTTTTTTT#####TTTTTTTTTTT#####TTT#TTTT######TTTTTT#####TTTTTTT#T#TTTTTTTT#TTTTTTTTTT#TTTTTTT........
.........TTTTTTTTTTTTTT#T#TTT#TTTTTTTTTTT#T#####TTTT###########TT#TTT#####TTT#TT#TT#####TT#TTTT##########TTTTT####TTTTTTTTTTTT#TTTTTTTTTTTT#TTTTTTTTT#.........
..........#TTT#TTTTTT#TTTTT#TTTTTTTTTTTTTTT####TTTT####TTT#####TTTTTTT####TTTTTTTTT####TTTTTTT######TTT###T#TTT####TTTTTTTTTTTTTTTT#TTTTTTTTT#T#TT#TT..........
...........TTTTTT#TTTTTTT#TTT#################TTTTT#############TT#TTTT####TTTTTTTT####TTTT#TT############TTTTT##################TTTTTT#T#TTTTTTTTTT...........
............#TTTTTTTTTTTTTTTT#################TT#TT############TTTTTTTT####TTT#TTT####TT#TTTTT############TTTTT##################T#T#TTTTTTTTTTTTTT............
.............TTTTTT#T#TTTTT#T####TTTTTTTTTTTTTTTTTTT##########TTT#TTTTT####T#TTTTT####TTTTTTTTT##########TTTTT#####TTTTTTTTT#####TTTTTTTTTTT#T#TTT.............
..............T#TTTTTTTTT#TTTT####TTTTTTTTT#####TTTTTT######TTTTTTT#TTT####TTTT#TTT####TTTT#TTTTT######TTTTT#T####TTTTTTTT######TTT#TTTT#T#TTTTTT..............
...............TT#TT#TTTTTTTTTTT#################TTTTTT#T#TTT#TTTTTTTTT####TT#TTT#TT####T#TTTTTTTTT#TTTTT#TTTT#####TTT#########TTTTTTTTTTTTTTTT#...............
................TTTTTTTTTT#TTT#TTTT###############TTTT#T#T#TTTT#T#TTTT####TTTTTTTTTT####TTTTTT#T#T#TTTTTTTT####################TT#TTTTT#TTTT#TT................
.................#TTT#TT#TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT#T#TTTTTTTTTT#####TTTT#T#TTTT######TTTTTTTTT#TTT#TTT###################TTTTTT#TTTTTTTTT.................
..................TTTTTTTTTTT#T#TTT#TTTTT#TT#####TTTTTTT#TTTTTTTTT######TTTTTTTTTT#TTT######TTTTTT#TTTTTTTTT#####TTTTTTTTTTTTTT#T#TTTTTTT#TTT..................
...................TTTTTTTT#TTTTTTTTT#TTTTTTT#########T#TT#T#TT#######TTTTTTTT#T#TTTTTT########TTTT#TTT########TTTTTTTTTTTTT#TTTTTTT#TT#TTT#...................
....................#TT#TTTTTTT#TT#TTTT#TTTTTTTT#######TTTTTTTT#####TTT#TT#TTTTTTTTTT#TTTT#####TTT#TTTT#######TTTTTTT#TT#TTTTTT#TTTTTTTTTTT....................
.....................TTTTTTTTTTTTTTT#TTTTTT#TTTT####TTTTT#TTT#TT####TTTTTTTTT#TT#TT#TTTTTT####TTTTT#TTTTTT####T#T#T#TTTTTTT#T#TTTTT#TTTT#T.....................
......................TTTT#TT#TTTTTTTTT#TTTTT#TT####T#T#TTTTTTTT####TTT#T#T#TTTTTTTTTTT#TT####TT#T#TT#TTTT####TTTTTTTTTTT#TTTTTTTTTTTT#TT......................
.......................#TTTTTTTT#TT#T#TTT#TTTTTT####TTTTTTTT#TTT####TTTTTTTTTT#T#TT#TTTTTT####TTTTT#TTTT#T####T#TT#TT#TTTTTTTTTTTTTT#TTT.......................
........................TT#TTTTTTTTTTTTTTTTTTTTT####TTT#T#TTTTTT####TTTTTTTTTTTTTTTTTTTTTT####T#TT#TTTTTTT####TTTTTTTTTT#TT#T#TTTTTTTTT........................
.........................TTT#TTTTT#TTTTTTTTTT#TT####TTTTTTTT#TTT#######T#T#T#T#T#T#T#T#T######TTTTT#TT#T#T####TTT#TTT#TTTTTTTTT#TT#TT#.........................
..........................TTTTT#TTTT#TTTTT#TTTTT####TTTTTT#TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT#TTTTTTT####T#TTT#TTTTTTTTTTTTTTTTT..........................
...........................T#TTTTT#TTTT#TTTTTTTT####TT#TTTTTT#####################################TTTTT#TT####TTTTTTTTTTT#TT#TTTT#TT...........................
............................TTTTTTTTT#TTT#TTTTTT####T###TTTTT#####################################TT#TTTTT####TT#TTTTTT#TTTTTTTTTTT............................
.............................#T#TTTTTTTTTTTTT#TT####TT##TTT#T#####TTTTTTTTTTTTTTTTTTTTTTTTTTT#####TTTTTTTT####TTTTT#T#TTTTT#TTTTT#.............................
..............................TTT#TTTTTTTT#TTTTT####TTTTT#TTTT#####TTTTTTT##TT#ETTT##TTTTT#T#####TTTTT###T####T#TTTTTTTTTTTTTT#TT..............................
...............................TTTTT#TT#TTTTT#TT#######T###TTTT####TTTTT#TT##TTTTT##TTTT#TTT####TTTTTTT#T#####TTTT#T#T#TTTTT#TTT...............................
................................TTTTTTTTTTTTTTTT####T##TTTTTTTTT#####TTTTTTT#######TTTTTTTT#####TTTTTTTTT####TTTTTTTTTTTTT#TTTT................................
.................................#TT#TTTT#T#TTTT####TTTTTT###TTTT########TTTTTTTTTTTTTT#######TTTT#T###TT####TTTTTTTT#TTTTTTT#.................................
..................................TTTT#TTTTTTTTTT####T###TT##TTTTTT########TTTT#TTTTT#######TTTTTTTT###T#####TTTTT#TTTT#TTTTT..................................
...................................TTTTT#TTTTTTTT#####T###TTT###TTTT########TTTTTTT########TTTTTTTTTTTT#####TTT#TTTTTTTTT#T#...................................
....................................T#TTTTTTT#T#TT#####TTTTTT####TTTT########TTTTT#####TTTTTTT#T###TTT#####TTTTTTT#TTT#TTTT....................................
.....................................TTTTTTTTTTTTTT#####TT##TTTTTT####TTTT####TTT###TTTTT#TTTTTT###TT#####TTTTT#TTTTTTTTTT.....................................
......................................#T#T#TTTTTTTTT#########TTTTTT###TTTTTTTTTTTTTTTTTTTTT###TTTTT######TTTT#TTTTT#TT#TT......................................
.......................................TTTTTT#TTT#TTTT######TTT#####TT##TTTT#TTTTTTTTTTTTTT###TTT######TTT#TTTTTTTTTTTTT.......................................
........................................#TTTTTT#TTTT#TT#######TTT##TTT###T#TTTT#TT#TT###TTTTT#T#######TTTTTTTTTTTTTTTT#........................................
.........................................TTTTTTTTTTTTTTTTT########TTTTTTTTTTTTTTTTTTTTTTTTT#########TTTTTT#T#T#TTTTTTT.........................................
..........................................T#TT#TT#TT#TTTTTTT############TTTTTTTTTTTTT############TTTTTTTTTTTTTTTTTT#T..........................................
...........................................TTTTTTTTTTTT#T#TTTTTT#############################TTTTTTTTTT#TT#TTTTTT#TT...........................................
............................................TTTTTTT#TTTTTTT#T#TTTTTTT####################TTTTTT#T#TT#TTTTTTT#TT#TTT............................................
.............................................#TT#TTTTTT#TTTTTTTT#TT#TTT#####TTTTTTT#####TTT#TTTTTTTTTT#T#TTTTTTTT#.............................................
..............................................TTTTTTT#TTTTTTTTTTTTTTTTT#####TTTTT#T#####TTTTTT#TT#T#TTTTTT#TT#TTT..............................................
...............................................TTTT#TTTTT#TT#T#T#TT#TTT#####TTTTTTT#####TT#TTTTTTTTTTTT#TTTTTTTT...............................................
................................................#TTTTT#TTTTTTTTTTTTTT#T#####TTTT#TT#####TTTTTTTTTTTT#TTTTTTTTT#................................................
.................................................TTTTTTTTT#TTT#TTTTTTTT#####TTTTTTT#####TTTTT#TT#TTTTTTTTTTTTT.................................................
..................................................TTTTTT#TTTTTTTT#TT#TT#####T#TT#TT#####TT#TTTTTTTTTTTTT#TT#T..................................................
...................................................#T#TTTTT#TTT#TTTTTTT#####TTTTTTT#####TTTTTTTTTTTTT#TTTTTT...................................................
....................................................TTTT#TTTTTTTTTTTTTT#####TT#TTTT#####TTTTTTTT#TTTTTTTTT#....................................................
.....................................................T#TTTTTTTT#############TTTTT#T############TTTTTTTTT#T.....................................................
......................................................TTTTTT################TTTTTTT###############TTTT#TT......................................................
.......................................................#####################TT#TTTT##################TTT.......................................................
........................................................TTTTTTTTTTTTTTTTTTTTTTTT#TTTTTTTTTTTTTTTTTTTTTT........................................................
.........................................................TTT#TTTTTTTT#T#TTTTTTTTTT#TTTTTTTTT#TTTTTTTTT.........................................................
..........................................................#TTTT#TT#TTTTTTTTTTTTTTTTT#TTTTT#TTT#TTTTT#..........................................................
...........................................................TT#TTTTTTT#TTTTTT#TT#T#TTTTT#TTTTTTTTT#TT...........................................................
............................................................TTTTTT#TTTT#T#TTTTTTTTTTT#TTTT#TTTTTTTT............................................................
.............................................................#TTTTTT#TTTTTTT#TTT#TTTTTTTTTTTTT#TT#.............................................................
..............................................................TT#TTTTTTTTT#TTTTTTTTTTTT#T#T#TTTTT..............................................................
...............................................................TTTTT#TTTTTTTTTTTTTTT#TTTTTTTTTTT...............................................................
................................................................TTTTTTT#T#TT#TTT#T#TTTT#TT#TTTT................................................................
.................................................................#TTT#TTTTTTTTTTTTTTTTTTTTTTTT.................................................................
..................................................................TTTTTT#TTTTTTTTTTT#T#TTT#TT..................................................................
...................................................................TTTTTTTT#TTT#TT#TTTTTTTTT...................................................................
....................................................................#TT#TTTTTTTTTTTTTT#TT#T....................................................................
.....................................................................TTTTTTT#TTTTTTTTTTTTT.....................................................................
......................................................................#TTT#TTTT#TT#TTTTTT......................................................................
.......................................................................T#TTTTTTTTTTT#TT#.......................................................................
........................................................................TTTTTTTTTTTTTTT........................................................................
.........................................................................#TT#TTTT#TTTT.........................................................................
..........................................................................TTTTT#TTTT#..........................................................................
...........................................................................#T#TTTT#T...........................................................................
............................................................................TTTTTTT............................................................................
.............................................................................TT#TT.............................................................................
..............................................................................TTT..............................................................................
...............................................................................S...............................................................................
""".strip().splitlines()

grid = [line.strip(".") for line in my_input]

for r, row in enumerate(grid):
    for c, char in enumerate(row):
        if char == "S": S = (r, c)
        if char == "E": E = (r, c)

def neighbors(r, c):
    if c > 0:
        yield (r, c - 1)
    if c < len(grid[r]) - 1:
        yield (r, c + 1)
    if c % 2 == 0:
        if r > 0:
            yield (r - 1, c + 1)
    else:
        yield (r + 1, c - 1)

seen = {S}
queue = deque([(0, S)])

while queue:
    dist, (cr, cc) = queue.popleft()
    for nr, nc in neighbors(cr, cc):
        if (nr, nc) == E:
            print(dist + 1)
            exit(0)
        if (nr, nc) in seen:
            continue
        if grid[nr][nc] == "#":
            continue
        seen.add((nr, nc))
        queue.append((dist + 1, (nr, nc)))


